### PR TITLE
Refine CUDA support.

### LINKED ISSUE #641: Fails compiling with cuda
I tried to build cuda code using the following build script:
```rust
    cc::Build::new()
        .cuda(true)
        .cudart("static")
        .flag("arch=sm_75")
        .flag("-std=c++17")
        .include("./testing/src")
        .file("testing/src/kernel.cu")
        .compile("libtesting.a");
```
And got the following error:
`  cargo:warning=nvcc fatal   : Unknown option '--target=x86_64-unknown-linux-gnu'`

Apparently nvcc doesn't like this flag.
full error:
```
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = Some("clang++ -stdlib=libc++")
  NVCC_x86_64-unknown-linux-gnu = None
  NVCC_x86_64_unknown_linux_gnu = None
  HOST_NVCC = None
  NVCC = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  running: "nvcc" "-ccbin=clang++" "-Xcompiler" "-O0" "-Xcompiler" "-ffunction-sections" "-Xcompiler" "-fdata-sections" "-Xcompiler" "-fPIC" "-G" "-Xcompiler" "-g" "-Xcompiler" "-fno-omit-frame-pointer" "--target=x86_64-unknown-linux-gnu" "-I" "./testing/src" "-Xcompiler" "-Wall" "-Xcompiler" "-Wextra" "arch=sm_75" "-std=c++17" "-o" .../src/kernel.o" "-c" "testing/src/kernel.cu"
  cargo:warning=nvcc fatal   : Unknown option '--target=x86_64-unknown-linux-gnu'
  exit status: 1

  --- stderr


  error occurred: Command "nvcc" "-ccbin=clang++" "-Xcompiler" "-O0" "-Xcompiler" "-ffunction-sections" "-Xcompiler" "-fdata-sections" "-Xcompiler" "-fPIC" "-G" "-Xcompiler" "-g" "-Xcompiler" "-fno-omit-frame-pointer" "--target=x86_64-unknown-linux-gnu" "-I" "./testing/src" "-Xcompiler" "-Wall" "-Xcompiler" "-Wextra" "arch=sm_75" "-std=c++17" "-o" "/.../src/kernel.o" "-c" "testing/src/kernel.cu" with args "nvcc" did not execute successfully (status code exit status: 1).
```

nvcc version:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Sep_13_19:13:29_PDT_2021
Cuda compilation tools, release 11.5, V11.5.50
Build cuda_11.5.r11.5/compiler.30411180_0
```

### PR DESCRIPTION
**Pull request by dot-asm**
Instead of counting all source files we count only .cu files, ones with device code that actually require the special treatment.

[Even fixes #641.]

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -1367,7 +1367,14 @@ impl Build {
         if !msvc || !is_asm || !is_arm {
             cmd.arg("-c");
         }
-        if self.cuda && self.files.len() > 1 {
+        if self.cuda
+            && self
+                .files
+                .iter()
+                .filter(|file| file.extension() == Some(OsStr::new("cu")))
```
Comment (thomcc) [inline src/lib.rs:1374]: Nit: can this be `.iter().any(|file| ...)` or is that prevented by MSRV.

File: src/lib.rs [hunk 2]
```diff
@@ -2035,7 +2042,14 @@ impl Build {
             self.assemble_progressive(dst, chunk)?;
         }
 
-        if self.cuda {
+        if self.cuda
```
Comment (thomcc) [inline src/lib.rs:2045]: Since you have this check (are we cuda and have \>1 .cu file), it's probably worth pulling out into a function.

**Review by thomcc — COMMENTED** [review]
Looks good but have some minor nits.

File: src/lib.rs (hunk 1 above)
Comment (dot-asm) [reply src/lib.rs:1374]: Documentation says "any() is short-circuiting," so one can't `.count()` it. One could use it in the second case, but since the suggestion is to make it a function for using in both cases, then it would have to be `.filter()`...

Comment (thomcc) [reply src/lib.rs:1374]: Oh right, yeah, `>1` rather than `>=1`, my bad.

File: src/lib.rs (hunk 2 above)
Comment (thomcc) [reply src/lib.rs:2045]: Nevermind, this is different.

Comment (dot-asm) [reply src/lib.rs:2045]: As in `if self.cuda && self.cuda_files_count() > X` or as in `if self.cuda_files_count() > X`?

Comment (dot-asm) [reply src/lib.rs:2045]: Well, a cuda_files_count() would make a sense, because the formatting is unbearable :-)

Comment (thomcc) [reply src/lib.rs:2045]: Yeah, that would be reasonable.

**Comment by dot-asm** [comment]
I used the opportunity to update the CUDA toolchain.

**Review by thomcc — APPROVED** [review]
This looks good to me.
