### PR TITLE
Fix broken link in docs.rs

### LINKED ISSUE #1172: Issue/Docs: Dead links and domain hijacking?
The "Compile-time Requirements" section contains a few dead links. The Win-builds link now goes to someones blog "if im wrong my bad!" when I think it should lead to here https://github.com/alex85k/winbuilds/blob/master/README.md

Another issue is the "here" link for MSYS2, the section/header it refers to no longer exists `https://github.com/rust-lang/rust#building-on-windows`.
The following looks like a good replacement.
https://github.com/rust-lang/rust/blob/master/INSTALL.md#building-on-windows

### PR DESCRIPTION
**Pull request by NobodyXu**
Fixed #1172

### CODE REVIEW

**Comment by NobodyXu** [comment]
cc @ChrisDenton can you take a look at this please?

There're some broken links in our docs.rs, on how to build on windows.

File: src/lib.rs [hunk 1]
```diff
@@ -141,14 +141,14 @@
 //! * Windows platforms targeting MinGW (e.g. your target triple ends in `-gnu`)
 //!   require `cc` to be available in `PATH`. We recommend the
 //!   [MinGW-w64](https://www.mingw-w64.org/) distribution, which is using the
-//!   [Win-builds](http://win-builds.org/) installation system.
+//!   [Win-builds](https://github.com/alex85k/winbuilds/blob/master/README.md) installation system.
```
Comment (ChrisDenton) [inline src/lib.rs:144]: Do we really need to link to win-builds? Why do users need to know what mingw-w64 is built on?

I'm asking because I think we should be very careful with third party links from official rust-lang documentation.

Comment (ChrisDenton) [reply src/lib.rs:144]: I think maybe we can just say we recommend `MinGW-w64` and leave it at that.

Comment (NobodyXu) [reply src/lib.rs]: Thanks, I've removed it

**Review by ChrisDenton — APPROVED** [review]
