### PR TITLE
Fix compilation on macOS using clang and fix compilation using zig-cc

### LINKED ISSUE #1362: error with 1.2.8 release
seeing some homebrew build issues with 1.2.8 release (1.2.7 works fine)

```
    error occurred in cc-rs: Command env -u IPHONEOS_DEPLOYMENT_TARGET LC_ALL="C" "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=arm64-apple-macosx15.2" "-DSQLITE_CORE" "-DSQLITE_DEFAULT_FOREIGN_KEYS=1" "-DSQLITE_ENABLE_API_ARMOR" "-DSQLITE_ENABLE_COLUMN_METADATA" "-DSQLITE_ENABLE_DBSTAT_VTAB" "-DSQLITE_ENABLE_FTS3" "-DSQLITE_ENABLE_FTS3_PARENTHESIS" "-DSQLITE_ENABLE_FTS5" "-DSQLITE_ENABLE_JSON1" "-DSQLITE_ENABLE_LOAD_EXTENSION=1" "-DSQLITE_ENABLE_MEMORY_MANAGEMENT" "-DSQLITE_ENABLE_RTREE" "-DSQLITE_ENABLE_STAT4" "-DSQLITE_SOUNDEX" "-DSQLITE_THREADSAFE=1" "-DSQLITE_USE_URI" "-DHAVE_USLEEP=1" "-DHAVE_ISNAN" "-D_POSIX_THREAD_SAFE_FUNCTIONS" "-DHAVE_LOCALTIME_R" "-o" "/private/tmp/oha-20250111-7621-jjkcal/oha-1.6.0/target/release/build/libsqlite3-sys-00ee1d36c89a7262/out/c877a2978823c39d-sqlite3.o" "-c" "--" "sqlite3/sqlite3.c" with args clang did not execute successfully (status code exit status: 1).
```

### PR DESCRIPTION
**Pull request by NobodyXu**
Fixed #1362 #1360

### CODE REVIEW

File: src/tool.rs [hunk 1]
```diff
@@ -428,10 +428,7 @@ impl Tool {
 
     /// Supports using `--` delimiter to separate arguments and path to source files.
     pub(crate) fn supports_path_delimiter(&self) -> bool {
-        matches!(
-            self.family,
-            ToolFamily::Clang { .. } | ToolFamily::Msvc { clang_cl: true }
-        ) && !self.cuda
+        matches!(self.family, ToolFamily::Msvc { clang_cl: true }) && !self.cuda
```
Comment (madsmtm) [inline src/tool.rs:431]: Nit: Would be nice to have a comment here that Homebrew doesn't support the flag, and that's why we don't use it on Clang.

**Review by madsmtm — APPROVED** [review]
Damn, Homebrew continues to be the bane of my existence... Looks good though.

File: src/tool.rs (hunk 1 above)
Comment (NobodyXu) [reply src/tool.rs:432]: Thanks, added

**Review by chenrui333 — APPROVED** [review]
the patch works for me. Thanks!

**Comment by chenrui333** [comment]
do you guys also plan a new release soonish? (need to refresh some of my PR updates)

**Comment by NobodyXu** [comment]
Yes within today

**Comment by chenrui333** [comment]
Thanks @NobodyXu! 🚀
